In [1]:
#importing libraries
import pandas as pd;
import numpy as np;

In [6]:
#Reading dataset
df = pd.read_excel('Raisin_Dataset.xlsx',header = None, na_values=' ?')

In [7]:
#First five rows of dataset
df.head()

,0,1,2,3,4,5,6,7
0,Area,MajorAxisLength,MinorAxisLength,Eccentricity,ConvexArea,Extent,Perimeter,Class
1,87524,442.246011,253.291155,0.819738,90546,0.758651,1184.04,Kecimen
2,75166,406.690687,243.032436,0.801805,78789,0.68413,1121.786,Kecimen
3,90856,442.267048,266.328318,0.798354,93717,0.637613,1208.575,Kecimen
4,45928,286.540559,208.760042,0.684989,47336,0.699599,844.162,Kecimen

In [11]:
#To check weather there is any NULL value in any column
df.isnull().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
dtype: int64

In [12]:
#To print information about dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 901 entries, 0 to 900
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       901 non-null    object
 1   1       901 non-null    object
 2   2       901 non-null    object
 3   3       901 non-null    object
 4   4       901 non-null    object
 5   5       901 non-null    object
 6   6       901 non-null    object
 7   7       901 non-null    object
dtypes: object(8)
memory usage: 56.4+ KB

In [13]:
#overview of dataset
df

,0,1,2,3,4,5,6,7
0,Area,MajorAxisLength,MinorAxisLength,Eccentricity,ConvexArea,Extent,Perimeter,Class
1,87524,442.246011,253.291155,0.819738,90546,0.758651,1184.04,Kecimen
2,75166,406.690687,243.032436,0.801805,78789,0.68413,1121.786,Kecimen
3,90856,442.267048,266.328318,0.798354,93717,0.637613,1208.575,Kecimen
4,45928,286.540559,208.760042,0.684989,47336,0.699599,844.162,Kecimen
...,...,...,...,...,...,...,...,...
896,83248,430.077308,247.838695,0.817263,85839,0.668793,1129.072,Besni
897,87350,440.735698,259.293149,0.808629,90899,0.636476,1214.252,Besni
898,99657,431.706981,298.837323,0.721684,106264,0.741099,1292.828,Besni
899,93523,476.344094,254.176054,0.845739,97653,0.658798,1258.548,Besni
900,85609,512.081774,215.271976,0.907345,89197,0.63202,1272.862,Besni

In [21]:
X = df.drop(columns = [7])

In [22]:
print(X);

         0                1                2             3           4  \
0     Area  MajorAxisLength  MinorAxisLength  Eccentricity  ConvexArea
1    87524       442.246011       253.291155      0.819738       90546
2    75166       406.690687       243.032436      0.801805       78789
3    90856       442.267048       266.328318      0.798354       93717
4    45928       286.540559       208.760042      0.684989       47336
..     ...              ...              ...           ...         ...
896  83248       430.077308       247.838695      0.817263       85839
897  87350       440.735698       259.293149      0.808629       90899
898  99657       431.706981       298.837323      0.721684      106264
899  93523       476.344094       254.176054      0.845739       97653
900  85609       512.081774       215.271976      0.907345       89197

            5          6
0      Extent  Perimeter
1    0.758651    1184.04
2     0.68413   1121.786
3    0.637613   1208.575
4    0.699599    844.162
..        ...        ...
896  0.668793   1129.072
897  0.636476   1214.252
898  0.741099   1292.828
899  0.658798   1258.548
900   0.63202   1272.862

[901 rows x 7 columns]